version: "2"
services:
  app:
    build: ./app
    ports:
      - "30000:5000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer
    ports:
      - "38000:8080"
